### ISSUE TITLE
为什么要拼接成字符串，存一个数组不是更好么

### ISSUE THREAD

**Issue by idy** [Angry-Chick/myapp#3]
https://github.com/Angry-Chick/myapp/blob/c70446af0ae9c7f710df79b71335ec19702b2c36/crawler.go#L71

**Comment by Angry-Chick** [comment]
因为 newData 是要存到全局 dataChannel 中，里面 map 的已经定好了是 string，而历史数据又依赖于 dataChannel，所以最好存放到 dataChannel 中
