### ISSUE TITLE
为什么 403 的错误是 IP 禁止访问

### ISSUE THREAD

**Issue by idy** [Angry-Chick/myapp#4]
https://github.com/Angry-Chick/myapp/blob/c70446af0ae9c7f710df79b71335ec19702b2c36/crawler.go#L48

**Comment by Angry-Chick** [comment]
403 状态码是服务器拒绝访问，在这里大概率是检测到咱们是爬虫所以封了 ip，可能考虑的不是很全面

**Comment by idy** [comment]
写这种代码不要去猜测场景 这种给人类读的文字描述 只有在 最后一道需要与人类交互的时候才定义

错误信息的传递尽量不要失去原始内容，http.Response 本身是有错误信息的
