### ISSUE TITLE
这是啥意思

### ISSUE THREAD

**Issue by idy** [Angry-Chick/myapp#5]
https://github.com/Angry-Chick/myapp/blob/c70446af0ae9c7f710df79b71335ec19702b2c36/crawler.go#L77

**Comment by Angry-Chick** [comment]
因为这一次拼接中 url 中末尾是带 xxxx.html ，通过这种方法将这个后缀去掉，然后添加新一次的 href

**Comment by Angry-Chick** [comment]
通过这种写死的方式截取似乎不太优雅，在实现了全部功能后会考虑通过正则表达式匹配
