### ISSUE TITLE
直接用 http.Get 就可以了

### ISSUE THREAD

**Issue by idy** [Angry-Chick/myapp#7]
https://github.com/Angry-Chick/myapp/blob/c70446af0ae9c7f710df79b71335ec19702b2c36/crawler.go#L95-L99

**Comment by Angry-Chick** [comment]
直接使用 get 不能设置 header 和其他信息，这个网页简单可能不需要，但是往后扩展我觉得可能需要设置一些属性，所以先写好了，如果不是很影响性能，这种写法似乎也不太累赘

**Comment by Angry-Chick** [comment]
有一些网站不喜欢被爬虫程序访问，所以会检测连接对象，如果是爬虫程序，就不能继续访问，通过设置User Agent 可以起到隐藏身份的目的，这个信息需要添加到请求头中
